### ISSUE TITLE
 TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by cmmartin** [jonschlinkert/project-name#1]
The `dirname` utility function will throw when passed undefined because it calls `path.resolve(dir);` and `path.resolve` must be passed a string

You can easily reproduce this by running `require('project-name')()` without a package.json

Tested in Node 4.2.0

**Comment by jonschlinkert** [comment]
good catch, thanks for creating the issue.

**Comment by jonschlinkert** [comment]
I wasn't able to reproduce the issue, but I did add code that _I think_ should fix the problem. Let me know  if this doesn't work for you and I'll take another look. thanks

**Comment by cmmartin** [comment]
Fixed. Thanks!

**Comment by jonschlinkert** [comment]
Thank you for letting me know!
